sonar.projectKey=WisePepper-tech_Smart-Backup
sonar.organization=wisepepper-tech
sonar.sources=.
sonar.exclusions=**/tests/**,**/*.txt
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml