apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: smart-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio@sha256:a1a8bd4ac40ad7881a245bab97323e18f971e4d4cba2c2007ec1bedd21cbaba2

        args:
          - server
          - /data
          - --console-address
          - ":9001"

        ports:
          - containerPort: 9000
          - containerPort: 9001

        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: smart-backup-secret
                key: S3_ACCESS_KEY
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: smart-backup-secret
                key: S3_SECRET_KEY

        volumeMounts:
          - name: data
            mountPath: /data

        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 10

        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000

        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data